MVC-GestionEleve/Models/ErrorViewModel.cs
using System;

namespace MVC_GestionEleve.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC-GestionEleve/Controllers/EleveController.cs
//using EleveService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SE1;
namespace MVC_GestionEleve.Controllers
{

    public class EleveController : Controller
    {

        private EleveServiceClient elc = new EleveServiceClient();

        public IActionResult Index()
        {
            
            ViewBag.listEleves = elc.findAll();
            return View();
        }
        public ActionResult Search(IFormCollection fc)
        {
            string cne = fc["cne"];
            ViewBag.listEleves = elc.findByCNE(Convert.ToString(cne));

            return View("Index");
        }
    }
}

MVC-GestionEleve/Controllers/ElevesCrudController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using S1;

namespace MVC_GestionEleve.Controllers
{
    public class ElevesCrudController : Controller
    {
        public Eleve Eleve{ get; set; }

        public ActionResult getEleves()
        {
            CrudElevesServicesClient o = new CrudElevesServicesClient();
            List<Eleve> li = o.GetEleves().ToList();
            ViewBag.List = li;

            return View();
        }
        //La methode suivante est pour afficher la vue (Displaying the view):
        public ActionResult insertEleve( )
        {
            return View();
        }
        //Les details de la form qu'on a poset doivent correspondre au details de l'objet objEleve , et on stock les données de post dans l'objet ObjEleve 
       [HttpPost]
        public ActionResult insertEleve(Eleve ObjEleve)
        {
            CrudElevesServicesClient o = new CrudElevesServicesClient();
            o.InsertEleve(ObjEleve);
            return View();
        }

        public ActionResult updateEleve()
        {
            return View();
        }
        [HttpPost]
        public ActionResult updateEleve(Eleve ObjEleve)
        {
           
       CrudElevesServicesClient o = new CrudElevesServicesClient();
            o.UpdateEleve(ObjEleve);
            return View();
        }
        public ActionResult deleteEleve()
        {
            return View();
        }
        [HttpPost]
        public ActionResult deleteEleve(int id)
        {
            CrudElevesServicesClient o = new CrudElevesServicesClient();
            o.DeleteEleve(id);
            return View();
        }
    }
}

MVC-GestionEleve/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_GestionEleve.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_GestionEleve.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC-GestionEleve/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Login1;
using S1;
namespace MVC_GestionEleve.Controllers
{
    public class LoginController : Controller
    {
        WcfServiceLoginClient login = new WcfServiceLoginClient();
    
        public ActionResult TestLog()
        {
            CrudElevesServicesClient o = new CrudElevesServicesClient();
            List<Eleve> li = o.GetEleves().ToList();
            ViewBag.List = li;
            return View();
         }

        [HttpPost]
        public ActionResult TestLog(string username,string password)
        {
            CrudElevesServicesClient o = new CrudElevesServicesClient();
            List<Eleve> li = o.GetEleves().ToList();
            ViewBag.List = li;

            if (login.LoginUserDetails(username, password) ==true)
            {
                /*Console.WriteLine("treu");*/
                return View("~/Views/ElevesCrud/getEleves.cshtml");
            }
            else
            {
                return View("LoginError");
            }
        }
        //[HttpPost]
        //public ActionResult TestLogin(IFormCollection fc)
        //{
        //    string u = fc["username"];
        //    string p = fc["password"];
        //    ViewBag.listEleves = login.LoginUserDetails(u, p);
        //    return View("Index");
        //}
     
    }
}

MVC-GestionEleve/Views/Eleve/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index Eleve</title>
</head>
<body>
    <h3>Liste des eleves</h3>

    @using (Html.BeginForm("search", "eleve"))
    {
        <span>Chercher par CNE</span> <input type="text" name="cne" />
        <input type="submit" value="Chercher" />
    }
    <br />
    <table cellpadding="2" cellspacing="2" border="1" class="table">
        <tr>
            <th>Id</th>
            <th>CNE</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Photo</th>
            <th>Tel</th>
            <th>Email</th>
        </tr>
        @foreach (var eleve in ViewBag.listEleves)
        {
            <tr>
                <td>@eleve.Id</td>
                <td>@eleve.CNE</td>
                <td>@eleve.Nom</td>
                <td>@eleve.Prenom</td>
                <td>    <a href="@eleve.Photo">image de @eleve.Prenom</a></td>
                <td>@eleve.Tel</td>
                <td>@eleve.Email</td>
            </tr>
        }

    </table>
</body>

</html>

MVC-GestionEleve/Views/ElevesCrud/deleteEleve.cshtml
@model CrudElevesServices.Eleve

@{
    ViewData["Title"] = "deleteEleve";
}

<h1>supprimer un eleve</h1>


    
    <form method="post" action="@Url.Action("deleteEleve")">

     Id : <input type="text" name="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger" /> 
    </form>

MVC-GestionEleve/Views/ElevesCrud/getEleves.cshtml
@{
    ViewBag.Title = "getEleves";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_GestionEleve</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <h2>Liste des eleves</h2>
    <div class="container" style="text-align:right;">

        <div class="col-12">
            <a class="btn btn-info " asp-area="" asp-controller="ElevesCrud" asp-action="updateEleve">Edit </a>
            <a class="btn btn-danger" asp-area="" asp-controller="ElevesCrud" asp-action="deleteEleve">Delete </a>
            <a class="btn btn-success" asp-area="" asp-controller="ElevesCrud" asp-action="insertEleve">Inserer un eleve</a>
        </div>
        <div>
            <br />

        </div>
        <table border="1" class="table" >
            <tr>
                <th style="text-align:center;">Id</th>
                <th style="text-align:center;">Cne</th>
                <th style="text-align:center;">Nom</th>
                <th style="text-align:center;">Prenom</th>
                <th style="text-align:center;">Photo</th>
                <th style="text-align:center;">Tel</th>
                <th style="text-align:center;">Email</th>

            </tr>
            @foreach (var item in ViewBag.List)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.CNE</td>
                    <td>@item.Nom</td>
                    <td>@item.Prenom</td>
                    <td> <a href="@item.Photo">image de @item.Prenom</a></td>
                    <td>@item.Tel</td>
                    <td>@item.Email</td>

                </tr>
            }
        </table>
    </div>
</body></html>

MVC-GestionEleve/Views/ElevesCrud/insertEleve.cshtml
@{
    ViewBag.Title = "insertEleve";
}
<h2>Inserer un eleve</h2>
<form method="post" action="@Url.Action("insertEleve")" class="col-12">
    <label class="col-1" >  Id  <input type="text" name="Id" /></label>
    <br />
    <label class="col-1" >
        CNE  <input type="text" name="CNE" />
    </label>
    <br />
    <label class="col-1" >
        Nom  <input type="text" name="Nom" />
    </label>
    <br />
    <label class="col-1" >  Prenom  <input type="text" name="Prenom" /></label>
    <br />
    <label class="col-1">  Photo <input type="text" name="Photo" /></label>
    <br />
    <label class="col-1"> Tel <input type="text" name="Tel" /></label>
    <br />

    <label class="col-1">  Email <input type="text" name="Email" /></label>
    <br />
    <label class="col-1">  <input type="submit" value="Insert" /></label>
    <br />

</form>

MVC-GestionEleve/Views/ElevesCrud/updateEleve.cshtml
@model MVC_GestionEleve.Controllers.ElevesCrudController
@{
    ViewBag.Title = "updateEleve";
}
<h2>Éditer un eleve</h2>
<form method="post" action="@Url.Action("updateEleve")" class="col-12">
    <label class="col-1">  Id   <input type="text" name="Id"   /></label>
    <br />
    <label  class="col-1">
        CNE  <input type="text" name="CNE" />
    </label>
    <br />
    <label class="col-1">
        Nom  <input type="text" name="Nom" />
    </label>
    <br />
    <label class="col-1">  Prenom  <input type="text" name="Prenom" /></label>
    <br />
    <label class="col-1">  Photo <input type="text" name="Photo" /></label>
    <br />
    <label class="col-1"> Tel <input type="text" name="Tel" /></label>
    <br />

    <label class="col-1">  Email <input type="text" name="Email" /></label>
    <br />
    <label class="col-1">  <input type="submit" value="Editer" /></label>
    <br />

</form>

MVC-GestionEleve/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC-GestionEleve/Views/Login/LoginError.cshtml
<h2 style="color:red">Incorrect username or password!</h2>

MVC-GestionEleve/Views/Login/TestLog.cshtml
@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html>

<body background="https://cdn.dribbble.com/users/3821226/screenshots/6761812/landscape_design-1.jpg">
    <form method="post" action="@Url.Action("TestLog")">

        <label class="col-1">  Username  <input type="text" name="username" /></label>
        <br />
        <label class="col-1">
            Password<input type="text" name="password" />
        </label>
        <br />
        <label class="col-1">
            <input type="submit" value="Login" class="btn btn-info" />
            </label>
    </form>


    @*@using (Html.BeginForm("", "ElevesCrud"))
        {<form method="post" action="@Url.Action("TestLogin")" class="col-12">
                <label>
                    <input type="submit" value="Login" />
                </label>
                <label class="col-1">  Username  <input type="text" name="username" /></label>
                <br />
                <label class="col-1">
                    Password<input type="text" name="password" />
                </label>
            </form>

        }*@

    @*<h2>Login</h2>
        <form method="post" action="@Url.TestLogin("updateEleve")" class="col-12">
            <label class="col-1">  Username  <input type="text" name="username" /></label>
            <br />
            <label class="col-1">
                Password  <input type="text" name="password" />
            </label>
            <br />
        </form>*@
</body>
</html>

MVC-GestionEleve/Views/Login/TestLogin.cshtml
@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html>

<body>
    <form method="post" action="@Url.Action("TestLogin")">

        <label class="col-1">  Username  <input type="text" name="username" /></label>
        <br />
        <label class="col-1">
            Password<input type="text" name="password" />
        </label>
        <input type="submit" value="Login" class="btn btn-danger" />
    </form>


    @*@using (Html.BeginForm("", "ElevesCrud"))
    {<form method="post" action="@Url.Action("TestLogin")" class="col-12">
            <label>
                <input type="submit" value="Login" />
            </label>
            <label class="col-1">  Username  <input type="text" name="username" /></label>
            <br />
            <label class="col-1">
                Password<input type="text" name="password" />
            </label>
        </form>

    }*@

    @*<h2>Login</h2>
        <form method="post" action="@Url.TestLogin("updateEleve")" class="col-12">
            <label class="col-1">  Username  <input type="text" name="username" /></label>
            <br />
            <label class="col-1">
                Password  <input type="text" name="password" />
            </label>
            <br />
        </form>*@
</body></html>

MVC-GestionEleve/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion élèves ENSAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" style="color:black" asp-area="" asp-controller="Home" asp-action="Index"> Gestion des élèves ENSAT </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="TestLog">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eleve" asp-action="Index">Espace eleve</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color:black">
            &copy; 2021 - Gestion des élèves ENSAT
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>